### ISSUE TITLE
Cannot find module 'stream.pipeline-shim/auto'

### ISSUE THREAD

**Issue by benzBrake** [SukkaW/nali-cli#14]
使用 npm 安装的，详细日志如下
```
node:internal/modules/cjs/loader:1056
  throw err;
  ^

Error: Cannot find module 'stream.pipeline-shim/auto'
Require stack:
- C:\Users\用户名\AppData\Roaming\nvm\v19.4.0\node_modules\nali-cli\util\qqwryUpdate.js
- C:\Users\用户名\AppData\Roaming\nvm\v19.4.0\node_modules\nali-cli\util\check-dat.js
- C:\Users\用户名\AppData\Roaming\nvm\v19.4.0\node_modules\nali-cli\lib\nali.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1053:15)
    at Module._load (node:internal/modules/cjs/loader:898:27)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at Object.<anonymous> (C:\Users\用户名\AppData\Roaming\nvm\v19.4.0\node_modules\nali-cli\util\qqwryUpdate.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1239:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\用户名\\AppData\\Roaming\\nvm\\v19.4.0\\node_modules\\nali-cli\\util\\qqwryUpdate.js',
    'C:\\Users\\用户名\\AppData\\Roaming\\nvm\\v19.4.0\\node_modules\\nali-cli\\util\\check-dat.js',
    'C:\\Users\\用户名\\AppData\\Roaming\\nvm\\v19.4.0\\node_modules\\nali-cli\\lib\\nali.js'
  ]
}

Node.js v19.4.0
```

**Comment by zongmingye** [comment]
macos使用yarn安装遇到相同报错
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module 'stream.pipeline-shim/auto'
Require stack:
- /Users/macos/.config/yarn/global/node_modules/nali-cli/util/qqwryUpdate.js
- /Users/macos/.config/yarn/global/node_modules/nali-cli/util/check-dat.js
- /Users/macos/.config/yarn/global/node_modules/nali-cli/lib/nali.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/macos/.config/yarn/global/node_modules/nali-cli/util/qqwryUpdate.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/macos/.config/yarn/global/node_modules/nali-cli/util/qqwryUpdate.js',
    '/Users/macos/.config/yarn/global/node_modules/nali-cli/util/check-dat.js',
    '/Users/macos/.config/yarn/global/node_modules/nali-cli/lib/nali.js'
  ]
}

Node.js v20.5.0

**Comment by grayguest** [comment]
同样的问题

$ nali
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'stream.pipeline-shim/auto'
Require stack:
....
.......

Node.js v18.18.0

**Comment by GodD6366** [comment]
```
npm install -g stream.pipeline-shim
# yarn add -g stream.pipeline-shim
```

安装下模块即可
